modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory
license = "${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

[[dependencies.megabotany]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.megabotany]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.megabotany]]
modId = "curios"
mandatory = true
versionRange = "[5.5.0+1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.megabotany]]
modId = "botania"
mandatory = true
versionRange = "[1.20.1-446,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.megabotany]]
modId = "jei"
mandatory = false
versionRange = "[1.20.1-15.8.0.18,)"
ordering = "NONE"
side = "CLIENT"